version: "3.9"
services:
  nginx:
    image: nginx:1.21.4-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
  php:
    build: .
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: always
    volumes:
      - .:/code
    depends_on:
      - nginx
