version: "3.9"
services:
  nginx:
    image: nginx:1.21.4-alpine
    restart: unless-stopped
    volumes:
      - ./etc/infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/gateway.com.conf
      - .:/var/www
    ports:
      - "80:80"
    depends_on:
      - php
    expose:
      - 80
  php:
    build: .
    ports:
      - "9000:9000"
    expose:
      - 9000
    restart: always
    volumes:
      - .:/var/www
    env_file:
      - .env
